# Railway deployment configuration
[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python main.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
PYTHON_VERSION = "3.12"
