#!/bin/bash
echo "=== BACKEND LOGS ==="
echo "Backend is running on port 8001"
echo "To see backend logs, check the terminal where you started it, or:"
echo "  - Visit http://localhost:8001/docs for API documentation"
echo "  - Check process: ps aux | grep 'python main.py'"
echo ""
echo "=== FRONTEND LOGS ==="
echo "Frontend is running on port 3000"
echo "To see frontend logs:"
echo "  - Check the terminal where you started 'npm start'"
echo "  - Or check browser console (F12)"
echo ""
echo "=== TESTING ENDPOINTS ==="
echo "Testing backend health..."
curl -s http://localhost:8001/health | python -m json.tool 2>/dev/null || echo "Backend not responding"
echo ""
echo "Testing auth endpoint..."
curl -s http://localhost:8001/api/auth/register -X POST -H "Content-Type: application/json" -d '{"email":"test@example.com","password":"test123","full_name":"Test User"}' 2>&1 | head -3
